require('./helpers/config-fixture.cjs');
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{EventEmitter}=require('node:events'),{createRequire}=require('node:module');
const core=require('../electron/core.cjs');
const calls=[];
class FakeRpc extends EventEmitter {constructor(){super();this.proc={pid:1};}async init(){}async end(){}async call(method,args){calls.push({method,args});if(method==='model/list')return {data:[{model:'gpt-5.6-sol',displayName:'Sol',supportedReasoningEfforts:[{reasoningEffort:'high'},{reasoningEffort:'xhigh'}],defaultReasoningEffort:'high',serviceTiers:[{id:'priority'}]}]};if(method==='account/read')return {account:{type:'chatgpt'}};if(method==='account/rateLimits/read')return {};if(method==='thread/start'||method==='thread/resume')return {thread:{id:'native-thread'}};if(method==='turn/start'){queueMicrotask(()=>this.emit('message',{method:'turn/completed',params:{turn:{status:'completed'}}}));return {turn:{id:'turn'}};}throw Error(method);}}
function load(file){const filename=path.resolve(__dirname,'../electron',file),realRequire=createRequire(filename),module={exports:{}};vm.runInNewContext(fs.readFileSync(filename,'utf8'),{module,exports:module.exports,require:id=>id==='./core.cjs'?{...core,Rpc:FakeRpc}:realRequire(id),__dirname:path.dirname(filename),process,Buffer,console,setTimeout,clearTimeout});return module.exports;}
const models=load('models.cjs'),{Runner}=load('runner.cjs');
test('catalog follows advertised tiers, including legacy fast, without guessing model support',()=>{assert.equal(models.fastServiceTier({serviceTiers:[{id:'priority'}]}),'priority');assert.equal(models.fastServiceTier({additionalSpeedTiers:['fast']}),'fast');assert.equal(models.fastServiceTier({}),null);assert.equal(models.fastServiceTier({serviceTiers:[{id:'ultrafast'}],additionalSpeedTiers:['fast']}),null);});
test('speed saves per account, survives reload, and rejects unsupported provider tiers',async()=>{const {root}=require('./helpers/config-fixture.cjs'),store=new core.TaskStore(path.join(root,'fast-tasks')),task=store.create({title:'Fast setting'}),profile=core.profileFor(task.profile),runner={active:{task}};assert.equal(models.selection(task,profile).serviceTier,'default');await models.updateSelectionForRunner(store,runner,task.id,{model:profile.model,effort:'xhigh',serviceTier:'priority'});const reloaded=new core.TaskStore(path.join(root,'fast-tasks')).get(task.id);assert.equal(models.selection(reloaded,profile).serviceTier,'priority');assert.equal(models.selection(reloaded,core.profileFor('codex-test-2')).serviceTier,'default');assert.equal(runner.active.task.modelSettings[profile.id].serviceTier,'priority');await assert.rejects(models.validateSelection(profile.id,task.cwd,{model:profile.model,effort:'high',serviceTier:'ultrafast'}),/速度/);await assert.rejects(models.validateSelection('claude-test-1',task.cwd,{model:'opus',effort:'high',serviceTier:'priority'}),/速度/);await models.saveSelection(store,reloaded,{model:profile.model,effort:'xhigh',serviceTier:'default'});assert.equal(models.selection(store.get(task.id),profile).serviceTier,'default');});
test('native start and resume explicitly request Fast then Standard without changing reasoning effort',async()=>{const {root}=require('./helpers/config-fixture.cjs'),store=new core.TaskStore(path.join(root,'fast-runs')),task=store.create({title:'Native tiers'}),base=core.profileFor(task.profile),runner=new Runner(store);for(const serviceTier of ['priority','default']){calls.length=0;const profile={...base,effort:'xhigh',serviceTier};task.execution={profile:base.id,model:base.model,effort:'xhigh',serviceTier};runner.active={task,profile};await runner.codex(task,profile,'test','');const thread=calls.find(c=>c.method.startsWith('thread/')),turn=calls.find(c=>c.method==='turn/start');assert.equal(thread.method,serviceTier==='priority'?'thread/start':'thread/resume');assert.equal(thread.args.serviceTier,serviceTier);assert.equal(turn.args.serviceTier,serviceTier);assert.equal(turn.args.effort,'xhigh');assert.equal(task.lastExecution.serviceTier,serviceTier);}});

test('simultaneous model controls share one discovery process',async()=>{models.invalidate('codex-test-3');calls.length=0;const results=await Promise.all([models.modelOptions('codex-test-3',process.cwd()),models.modelOptions('codex-test-3',process.cwd())]);assert.equal(calls.filter(c=>c.method==='model/list').length,1);assert.equal(results[0],results[1]);});

test('Codex turn receives linked writable roots and preserves read-only policy',async()=>{const {root}=require('./helpers/config-fixture.cjs'),linked=path.join(root,'linked'),store=new core.TaskStore(path.join(root,'root-runs'));fs.mkdirSync(linked,{recursive:true});const task=store.create({title:'Multi-root',cwd:root}),profile=core.profileFor(task.profile),runner=new Runner(store);task.linkedProjects=[linked];for(const mode of ['workspace-write','read-only']){calls.length=0;task.execution={mode};runner.active={task,profile};await runner.codex(task,profile,'test','');const policy=calls.find(c=>c.method==='turn/start').args.sandboxPolicy;if(mode==='workspace-write')assert.deepEqual(Array.from(policy.writableRoots),[root,fs.realpathSync.native(linked)]);else {assert.equal(policy.type,'readOnly');assert.equal(policy.writableRoots,undefined);}}});
