require('./helpers/config-fixture.cjs');
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {TaskStore}=require('../electron/core.cjs'),{Runner}=require('../electron/runner.cjs');
const {normalizeRoots,validateAccess,codexSandbox}=require('../electron/project-access.cjs');
const {updateTaskSetting}=require('../electron/task-settings.cjs'),{manageTask}=require('../electron/task-actions.cjs');
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'prism-links-'));t.after(()=>{assert.equal(path.dirname(fs.realpathSync(root)).toLowerCase(),fs.realpathSync(os.tmpdir()).toLowerCase());fs.rmSync(root,{recursive:true,force:true});});const a=path.join(root,'A'),b=path.join(root,'B');fs.mkdirSync(a);fs.mkdirSync(b);const store=new TaskStore(path.join(root,'tasks')),runner=new Runner(store),task=store.create({cwd:a,title:'Keep history',mode:'workspace-write'});return {root,a,b,store,runner,task};}
test('explicit directory links normalize, persist and preserve task permission and history',t=>{const{a,b,store,runner,task}=fixture(t);store.append(task.id,'user',{text:'Keep this request'});task.sessions={one:'native-session'};store.save(task);const updated=updateTaskSetting(store,runner,task.id,{linkedProjects:[a,b,b]});assert.deepEqual(updated.linkedProjects,[fs.realpathSync.native(b)]);assert.equal(updated.cwd,a);assert.equal(updated.mode,'workspace-write');assert.deepEqual(updated.sessions,{});assert.equal(store.events(task.id)[0].text,'Keep this request');assert.deepEqual(codexSandbox(updated).writableRoots,[a,fs.realpathSync.native(b)]);assert.equal(codexSandbox({...updated,mode:'read-only'}).type,'readOnly');assert.equal(codexSandbox({...updated,mode:'full-access'}).type,'dangerFullAccess');});
test('invalid links and live changes are rejected without widening stored roots',t=>{const{a,b,store,runner,task}=fixture(t);for(const values of [['relative'],[path.join(a,'missing')],'all',Array(33).fill(b)])assert.throws(()=>normalizeRoots(a,values));runner.active={task};assert.throws(()=>updateTaskSetting(store,runner,task.id,{linkedProjects:[b]}),/停止/);assert.equal(store.get(task.id).linkedProjects,undefined);assert.throws(()=>validateAccess({...task,linkedProjects:[b]},{provider:'Grok'}),/Codex/);assert.doesNotThrow(()=>validateAccess({...task,mode:'full-access',linkedProjects:[b]},{provider:'Grok'}));});
test('dragging moves the conversation, keeps source project available and rejects a live move',async t=>{const{a,b,store,runner,task}=fixture(t);task.pinned=true;task.sessions={one:'old-session'};store.save(task);store.append(task.id,'assistant',{text:'Existing output'});const moved=manageTask(store,runner,null,task.id,'project-move',b);assert.equal(moved.cwd,fs.realpathSync.native(b));assert.equal(moved.pinned,false);assert.deepEqual(moved.sessions,{});assert.equal(store.events(task.id)[0].text,'Existing output');const {sidebarGroups}=await import('../src/sidebar-groups.js');assert.equal(sidebarGroups([moved])[1].groups.length,2);assert.equal(sidebarGroups([moved])[1].groups.find(g=>g.path===a).tasks.length,0);runner.active={task:moved};assert.throws(()=>manageTask(store,runner,null,task.id,'project-move',a),/停止/);assert.equal(store.get(task.id).cwd,fs.realpathSync.native(b));});
test('automatic relay preserves linked-directory support',async t=>{const{b,store,runner,task}=fixture(t);task.linkedProjects=[b];task.mode='read-only';task.relayOrder=['grok-test-1','gemini-test-1','claude-test-1'];store.save(task);const visited=[];runner.codex=async function(task,profile){visited.push(profile.provider);this.active.quotaExhausted=true;this.state(task,'failed');};runner.claude=async function(task,profile){visited.push(profile.provider);this.state(task,'idle');};runner.grok=runner.gemini=async()=>assert.fail('Restricted links cannot silently relay to unsupported providers');await runner.run(task.id,'Continue');assert.deepEqual(visited,['Codex','Claude']);});
