require('./helpers/config-fixture.cjs');
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {TaskStore,PROFILES,childEnv,profileFor}=require('../electron/core.cjs');const {Runner}=require('../electron/runner.cjs');const {normalizeClaude,codexExhausted}=require('../electron/quota.cjs');
test('cached weekly exhaustion survives an allowed short window and expires at reset',t=>{const{root}=fixture(t);const prior=process.env.PRISM_TEST_DATA;process.env.PRISM_TEST_DATA=root;t.after(()=>{if(prior===undefined)delete process.env.PRISM_TEST_DATA;else process.env.PRISM_TEST_DATA=prior;});const{recordClaude,cachedQuota}=require('../electron/quota.cjs');const now=Date.now(),reset=Math.floor(now/1000)+60;recordClaude('claude-test-1',{status:'rejected',rateLimitType:'seven_day',resetsAt:reset});recordClaude('claude-test-1',{status:'allowed',rateLimitType:'five_hour',utilization:0.2,resetsAt:reset+500});assert.equal(cachedQuota('claude-test-1').remaining,0);assert.equal(cachedQuota('claude-test-1').exhausted,true);assert.equal(cachedQuota('claude-test-1',now+61000).remaining,80);assert.equal(cachedQuota('claude-test-1',now+301000).remaining,null);});
test('Codex expired windows do not manufacture exhausted quota',()=>{const{quotaView}=require('../electron/core.cjs');assert.equal(quotaView({rateLimits:{limitId:'codex',primary:{usedPercent:100,resetsAt:1},secondary:{usedPercent:20,resetsAt:Date.now()/1000+1000}}}).remaining,80);});
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'prism-relay-'));t.after(()=>{const real=fs.realpathSync.native(root);assert.equal(path.dirname(real).toLowerCase(),fs.realpathSync.native(os.tmpdir()).toLowerCase());assert.ok(path.basename(real).startsWith('prism-relay-'));fs.rmSync(real,{recursive:true,force:true});});const store=new TaskStore(path.join(root,'tasks'));const task=store.create({title:'接续测试',cwd:root});return {root,store,task,runner:new Runner(store)};}
test('automatic relay waits for previous execution and records the original request once',async t=>{const{root,store,task,runner}=fixture(t);let release;const barrier=new Promise(r=>release=r);let calls=0;runner.codex=async function(task,profile,text){calls++;if(calls===1){this.active.started=true;fs.writeFileSync(path.join(root,'progress'),'first');await barrier;this.active.quotaExhausted=true;this.state(task,'failed');}else{assert.equal(fs.readFileSync(path.join(root,'progress'),'utf8'),'first');assert.match(text,/不得重复/);this.state(task,'idle');}};const promise=runner.run(task.id,'原始用户需求');assert.throws(()=>runner.switch(task.id,'codex-test-3'));assert.equal(calls,1);release();await promise;assert.equal(calls,2);assert.equal(store.events(task.id).filter(e=>e.type==='user').length,1);assert.equal(store.get(task.id).id,task.id);assert.equal(store.get(task.id).state,'idle');});
test('network or unknown completion never triggers replay',async t=>{const{store,task,runner}=fixture(t);let calls=0;runner.codex=async function(){calls++;this.active.started=true;throw Error('network disconnected');};await runner.run(task.id,'修改项目');assert.equal(calls,1);assert.equal(store.get(task.id).state,'unknown');});
test('user cancellation and disabled automatic relay suppress account switching',async t=>{for(const disable of [true,false]){const{store,task,runner}=fixture(t);task.autoSwitch=!disable;store.save(task);let calls=0;runner.codex=async function(task){calls++;this.active.quotaExhausted=true;if(!disable)this.active.cancelRequested=true;this.state(task,'failed');};await runner.run(task.id,'继续');assert.equal(calls,1);}});
test('exhausted pool is bounded and never retries any profile',async t=>{const{store,task,runner}=fixture(t);const visited=[];const fail=async function(task,profile){assert.ok(!visited.includes(profile.id));visited.push(profile.id);this.active.quotaExhausted=true;this.state(task,'failed');};runner.codex=runner.claude=runner.grok=runner.gemini=fail;await runner.run(task.id,'只读研究');assert.equal(visited.length,PROFILES.length);assert.equal(store.events(task.id).filter(e=>e.type==='user').length,1);});
test('Grok cannot silently receive a file-writing task',t=>{const{store,task,runner}=fixture(t);task.mode='workspace-write';store.save(task);assert.throws(()=>runner.switch(task.id,'grok-test-1'),/只读/);});
test('write-enabled Grok receives an exhausted writer task and preserves its progress',async t=>{
 const {root,store,task,runner}=fixture(t),grok=profileFor('grok-test-1');
 const original=grok.write;grok.write=true;t.after(()=>grok.write=original);
 task.mode='workspace-write';task.relayOrder=[task.profile,grok.id];store.save(task);
 runner.codex=async function(task){fs.writeFileSync(path.join(root,'progress'),'first');this.active.quotaExhausted=true;this.state(task,'failed');};
 const images=[{path:path.join(root,'image.png')}];
 runner.grok=async function(task,profile){assert.equal(profile.id,grok.id);assert.equal(task.execution.mode,'workspace-write');assert.deepEqual(this.active.images,images);assert.equal(fs.readFileSync(path.join(root,'progress'),'utf8'),'first');this.state(task,'idle');};
 await runner.run(task.id,'Continue writing',images);assert.equal(store.get(task.id).profile,grok.id);assert.equal(store.get(task.id).state,'idle');
 assert.equal(store.events(task.id).filter(e=>e.type==='user').length,1);
});
test('only structured quota evidence can trigger a relay',()=>{assert.equal(codexExhausted({message:'usageLimitExceeded'}),false);assert.equal(codexExhausted({codexErrorInfo:'rateLimitExceeded'}),false);assert.equal(codexExhausted({codexErrorInfo:'usageLimitExceeded'}),true);assert.equal(normalizeClaude({status:'rejected',rateLimitType:'overage'}).exhausted,false);assert.equal(normalizeClaude({status:'rejected',rateLimitType:'seven_day_opus'}).exhausted,true);assert.equal(normalizeClaude({status:'allowed'}).remaining,null);assert.equal(normalizeClaude({status:'allowed',utilization:0.25,rateLimitType:'five_hour'}).remaining,75);assert.equal(normalizeClaude({status:'allowed',utilization:25}).remaining,null);});
test('Grok auth paths are isolated and API keys are excluded',()=>{const a=childEnv(profileFor('grok-test-1')),b=childEnv(profileFor('grok-test-3'));assert.notEqual(a.GROK_AUTH_PATH,b.GROK_AUTH_PATH);assert.equal(a.XAI_API_KEY,undefined);assert.equal(a.GROK_DEPLOYMENT_KEY,undefined);});
