require('./helpers/config-fixture.cjs');
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {TaskStore}=require('../electron/core.cjs'),{manageTask}=require('../electron/task-actions.cjs');
test('task deletion and archive preserve files, remove queued work, and support durable restore',t=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'prism-task-actions-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const store=new TaskStore(root),task=store.create({title:'Keep files'});fs.writeFileSync(path.join(task.cwd,'document.txt'),'original');const queue={items:[{taskId:task.id},{taskId:'other'}],save(){}};
 manageTask(store,{},queue,task.id,'delete');assert.equal(store.list().length,0);assert.equal(store.list('deleted').length,1);assert.throws(()=>store.get(task.id));assert.equal(queue.items.length,1);assert.equal(fs.readFileSync(path.join(task.cwd,'document.txt'),'utf8'),'original');
 const reopened=new TaskStore(root);manageTask(reopened,{},queue,task.id,'restore');assert.equal(reopened.get(task.id).cwd,task.cwd);manageTask(reopened,{},queue,task.id,'archive');assert.equal(reopened.list().length,0);assert.equal(reopened.list('archived').length,1);manageTask(reopened,{},queue,task.id,'restore');assert.equal(reopened.list().length,1);
 const active={active:{task:reopened.get(task.id)}};assert.throws(()=>manageTask(reopened,active,queue,task.id,'delete'));manageTask(reopened,active,queue,task.id,'pin');assert.equal(active.active.task.pinned,true);manageTask(reopened,active,queue,task.id,'unread');assert.equal(reopened.get(task.id).unread,true);
});
test('forks preserve conversation and attachments while isolating CLI sessions and optional workspaces',async t=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'prism-fork-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const store=new TaskStore(root),source=store.create({title:'Source'});source.sessions={codex:'private-session'};store.save(source);fs.writeFileSync(path.join(source.cwd,'original.txt'),'keep');const attachments=path.join(store.dir(source.id),'attachments');fs.mkdirSync(attachments);fs.writeFileSync(path.join(attachments,'image.png'),'image-bytes');store.append(source.id,'user',{text:'Hello',images:[{id:'image',name:'Sketch',path:path.join(attachments,'image.png')}]});store.append(source.id,'tool',{text:'internal detail'});
 const {forkTask,conversationText}=require('../electron/task-actions.cjs');const shared=await forkTask(store,{},source.id),independent=await forkTask(store,{},source.id,true);assert.equal(shared.cwd,source.cwd);assert.notEqual(independent.cwd,source.cwd);assert.deepEqual(fs.readdirSync(independent.cwd),[]);assert.deepEqual(shared.sessions,{});assert.equal(store.events(shared.id)[0].text,'Hello');assert.equal(fs.readFileSync(store.events(shared.id)[0].images[0].path,'utf8'),'image-bytes');assert.ok(!conversationText(store,source.id).includes('internal detail'));assert.ok(fs.existsSync(path.join(source.cwd,'original.txt')));
 manageTask(store,{},null,source.id,'project',independent.cwd);assert.deepEqual(store.get(source.id).sessions,{});assert.ok(store.get(source.id).previousWorkspaces.includes(source.cwd));
});
test('native menu contains functional actions, nested destinations and familiar accelerators',()=>{
 const {taskMenuTemplate}=require('../electron/task-menu.cjs');let selected;const template=taskMenuTemplate({cwd:'project'},[{section:'Writing',cwd:'project',projectGroup:true}],x=>x,x=>selected=x);const leaves=template.flatMap(x=>x.submenu||[x]).filter(x=>x.click);for(const item of leaves){item.click();assert.ok(selected.action);}assert.equal(template[0].accelerator,'Alt+Ctrl+R');assert.ok(leaves.some(x=>x.label==='Writing'));const busy=taskMenuTemplate({},[],x=>x,()=>{},true);assert.equal(busy.find(x=>x.label==='删除任务').enabled,false);
});
