require('./helpers/config-fixture.cjs');
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {root}=require('./helpers/config-fixture.cjs');const {TaskStore,environmentPrompt,profileFor}=require('../electron/core.cjs');const {Runner}=require('../electron/runner.cjs');const plans=require('../electron/task-plan.cjs');
function fixture(){const store=new TaskStore(path.join(root,'plan-tasks'));const task=store.create({title:'Planning test',cwd:root,mode:'full-access'});return {store,task,runner:new Runner(store)};}
test('plans persist in handoff and reject stale edits while remaining available during a run',()=>{const{store,task,runner}=fixture();runner.active={task};const saved=plans.save(store,runner,task.id,{goal:'Ship the game',steps:[{text:'Verify collisions',status:'pending'}]});assert.equal(runner.active.task.workPlan.goal,'Ship the game');assert.throws(()=>plans.save(store,runner,task.id,{goal:'stale',steps:[]}),/计划已更新/);assert.match(fs.readFileSync(store.context(saved).path,'utf8'),/Verify collisions/);assert.equal(store.get(task.id).workPlan.revision,saved.workPlan.revision);});
test('planning enforces read-only, preserves configured permission, imports steps, and requires confirmation',async()=>{const{store,task,runner}=fixture();plans.save(store,runner,task.id,{goal:'Build test',steps:[]});runner.codex=async function(t,p,text,instructions){assert.equal(t.mode,'full-access');assert.equal(t.execution.mode,'read-only');assert.match(instructions,/禁止修改文件/);this.confirmExecution(t,p);this.event(t.id,'assistant',{text:'```json\n{"steps":[{"text":"Review first"}]}\n```'});this.state(t,'idle');};await runner.run(task.id,'Plan only',[],{planning:true});const saved=store.get(task.id);assert.equal(saved.workPlan.steps[0].text,'Review first');assert.equal(saved.planReviewRequired,true);assert.equal(saved.mode,'full-access');await assert.rejects(runner.run(task.id,'execute'),/确认/);});
test('generated plans do not overwrite edits made while the model runs',()=>{const t={workPlan:{goal:'new',steps:[],revision:'new'}};assert.equal(plans.capture(t,[{type:'plan',data:{plan:[{step:'old'}]}}],'old'),false);assert.equal(t.workPlan.goal,'new');});
test('large plans are complete on disk but bounded in subprocess instructions',()=>{const{store,task,runner}=fixture();plans.save(store,runner,task.id,{goal:'G'.repeat(4000),steps:[{text:'S'.repeat(1000),status:'pending'}]});const current=store.get(task.id);assert.ok(plans.context(current,true).length<2000);assert.ok(plans.context(current).length>5000);assert.ok(environmentPrompt(current,{apps:[]},store.context(current)).length<5000);});
test('confirmed model changes are recorded, starting alone is not a success',async()=>{const{store,task,runner}=fixture();runner.codex=async function(t,p){assert.equal(t.execution.confirmed,undefined);this.confirmExecution(t,p);this.state(t,'idle');};await runner.run(task.id,'first');let current=store.get(task.id);current.modelSettings={[task.profile]:{model:'another-model',effort:'max'}};store.save(current);await runner.run(task.id,'second');current=store.get(task.id);assert.equal(current.lastExecution.model,'another-model');assert.equal(current.lastExecution.effort,'max');assert.match(store.events(task.id).findLast(e=>e.execution).text,/已切换/);runner.confirmExecution(current,profileFor(current.profile));});
test('automatic handoff honors task priority and carries the chosen model across providers',async()=>{const{store,task,runner}=fixture();task.relayOrder=['claude-test-2'];task.modelSettings={'claude-test-2':{model:'sonnet',effort:'high'}};store.save(task);runner.codex=async function(t){this.active.quotaExhausted=true;this.state(t,'failed');};runner.claude=async function(t,p){assert.equal(p.id,'claude-test-2');assert.equal(p.model,'sonnet');assert.equal(p.effort,'high');this.confirmExecution(t,p,'claude-sonnet');this.state(t,'idle');};await runner.run(task.id,'continue');assert.equal(store.get(task.id).profile,'claude-test-2');assert.equal(store.get(task.id).lastExecution.reportedModel,'claude-sonnet');});
