const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {Updater,command}=require('../electron/updater.cjs');
const {write,read,versionPath,validVersion,bootstrap,healthy}=require('../electron/update-bootstrap.cjs');
const OLD='a'.repeat(40),NEW='b'.repeat(40);
function setup(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'prism-updater-'));t.after(()=>{assert.equal(path.dirname(fs.realpathSync(root)).toLowerCase(),fs.realpathSync(os.tmpdir()).toLowerCase());assert.ok(path.basename(root).startsWith('prism-updater-'));fs.rmSync(root,{recursive:true,force:true});});for(const file of ['electron/main.cjs','runtime/node/node.exe','node_modules/npm/bin/npm-cli.js']){fs.mkdirSync(path.dirname(path.join(root,file)),{recursive:true});fs.writeFileSync(path.join(root,file),'fixture');}write(path.join(root,'package.json'),{name:'prism-desk',version:'0.1.0'});return root;}
function artifacts(dir){for(const file of ['electron/main.cjs','electron/update-bootstrap.cjs','runtime/node/node.exe','node_modules/npm/bin/npm-cli.js','dist/index.html','runtime/desktop/Prism.exe','runtime/PrismProcess.exe']){fs.mkdirSync(path.dirname(path.join(dir,file)),{recursive:true});fs.writeFileSync(path.join(dir,file),'fixture');}}
function fake(root,options={}){const calls=[];return {calls,fetchRelease:async()=>({version:'0.2.0',tag:'v0.2.0',body:'New release',publishedAt:'2026-09-09T00:00:00Z'}),run:async(file,args,cwd)=>{calls.push({file,args,cwd});if(args[0]==='rev-parse')return cwd===root?OLD:NEW;if(args[0]==='ls-remote'){if(options.offline)throw Error('Network unavailable');return NEW+'\trefs/tags/v0.2.0';}if(args[0]==='checkout')write(path.join(cwd,'package.json'),{version:'0.2.0'});if(args[0]==='status')return options.dirty?' M source.cjs':'';if(args[0]==='clone')fs.mkdirSync(args.at(-1),{recursive:true});if(args.some(a=>a.endsWith('build-host.ps1'))){if(options.buildFail)throw Error('Compiler failed');artifacts(cwd);}return '';}};}
test('check is real revision based and automatic preference survives restart',async t=>{const root=setup(t),f=fake(root),u=new Updater(root,{...f,platform:'win32'});assert.equal((await u.check()).status,'available');assert.equal(u.state.latest,NEW);u.automatic(false);assert.equal(new Updater(root,{...f,platform:'win32'}).state.automatic,false);assert.deepEqual(f.calls.find(c=>c.args[0]==='ls-remote').args,['ls-remote','https://github.com/shixi-11/prism-desk.git','refs/tags/v0.2.0','refs/tags/v0.2.0^{}']);});
test('ordinary commits, equal versions and older releases never prompt an update',async t=>{
 const root=setup(t),f=fake(root);write(path.join(root,'package.json'),{version:'0.2.0'});
 const u=new Updater(root,{...f,platform:'win32'});assert.equal((await u.check()).status,'current');assert.equal(u.state.latest,OLD);
 u.fetchRelease=async()=>({version:'0.1.0',tag:'v0.1.0',body:'older'});assert.equal((await u.check()).status,'current');
 u.fetchRelease=async()=>null;assert.equal((await u.check()).status,'current');assert.equal(f.calls.some(call=>call.args[0]==='ls-remote'||call.args[0]==='clone'),false);
});
test('annotated release tags resolve to their peeled commit and checking never installs',async t=>{
 const root=setup(t),f=fake(root),u=new Updater(root,{...f,run:async(file,args,cwd)=>args[0]==='ls-remote'?'c'.repeat(40)+'\trefs/tags/v0.2.0\n'+NEW+'\trefs/tags/v0.2.0^{}':f.run(file,args,cwd),platform:'win32'});
 const state=await u.check();assert.equal(state.latest,NEW);assert.equal(state.release.version,'0.2.0');assert.equal(state.release.body,'New release');assert.equal(fs.existsSync(u.activeFile),false);assert.equal(fs.existsSync(versionPath(root,NEW)),false);
});
test('downloaded package version must match the release before any install commands',async t=>{
 const root=setup(t),f=fake(root),u=new Updater(root,{...f,run:async(file,args,cwd)=>{const value=await f.run(file,args,cwd);if(args[0]==='checkout')write(path.join(cwd,'package.json'),{version:'0.9.0'});return value;},platform:'win32'});
 await u.check();assert.equal((await u.prepare()).status,'error');assert.match(u.state.error,/版本号/);assert.equal(f.calls.some(call=>call.args.includes('ci')),false);assert.equal(fs.existsSync(u.activeFile),false);
});
test('dirty source prevents preparation without cloning or overwriting',async t=>{const root=setup(t),f=fake(root,{dirty:true}),u=new Updater(root,{...f,platform:'win32'});await u.check();assert.equal((await u.prepare()).status,'error');assert.equal(f.calls.some(c=>c.args[0]==='clone'),false);assert.equal(fs.existsSync(u.activeFile),false);});
test('failed build leaves active installation intact and next attempt can retry',async t=>{const root=setup(t),options={buildFail:true},f=fake(root,options),u=new Updater(root,{...f,platform:'win32'});write(u.activeFile,{current:OLD});await u.check();assert.equal((await u.prepare()).status,'error');assert.equal(read(u.activeFile).current,OLD);assert.equal(fs.existsSync(versionPath(root,NEW)),false);options.buildFail=false;assert.equal((await u.prepare()).status,'ready');assert.equal(validVersion(root,NEW),true);assert.equal(read(u.activeFile).current,OLD);await u.activate();assert.equal(read(u.activeFile).current,NEW);assert.equal(read(u.activeFile).previous,OLD);assert.equal(read(u.activeFile).pending,true);assert.equal(f.calls.some(c=>c.args.includes('merge-base')),true);});
test('offline checks preserve current files and concurrent requests cannot start two downloads',async t=>{const root=setup(t),f=fake(root,{offline:true}),u=new Updater(root,{...f,platform:'win32'});assert.equal((await u.check()).status,'error');assert.equal(fs.existsSync(u.activeFile),false);u.busy=true;u.state.latest=NEW;assert.equal((await u.prepare()).status,'error');assert.equal(f.calls.some(c=>c.args[0]==='clone'),false);assert.throws(()=>versionPath(root,'../escape'));});
test('launcher redirects only to a complete version and readiness commits health',t=>{const root=setup(t),dir=versionPath(root,NEW);artifacts(dir);write(path.join(dir,'.local/ready.json'),{revision:NEW});write(path.join(dir,'.local/installation.json'),{root});const file=path.join(root,'.local/updates/active.json');write(file,{current:NEW,pending:true,attempted:Date.now()});let launched;const app={relaunch:value=>{launched=value;},exit:()=>{}};bootstrap(app,root);assert.equal(launched.execPath,path.join(dir,'runtime/desktop/Prism.exe'));healthy(dir);assert.equal(read(file).pending,false);});
test('unhealthy or incomplete version falls back without deleting user data or old code',t=>{const root=setup(t),dir=versionPath(root,NEW);artifacts(dir);write(path.join(dir,'.local/ready.json'),{revision:NEW});const file=path.join(root,'.local/updates/active.json');write(file,{current:NEW,previous:null,pending:true,attempted:Date.now()-180000});bootstrap({relaunch:()=>assert.fail('must stay on original'),exit:()=>{}},root);assert.equal(read(file).current,null);assert.equal(read(file).failed,NEW);assert.equal(fs.existsSync(dir),true);write(file,{current:OLD,previous:null});bootstrap({relaunch:()=>assert.fail('missing version must not launch'),exit:()=>{}},root);assert.equal(read(file).current,null);});
test('a rapid retry rolls back without refreshing its deadline; pinned versions return to the stable root',t=>{const root=setup(t),dir=versionPath(root,NEW);artifacts(dir);write(path.join(dir,'.local/ready.json'),{revision:NEW});write(path.join(dir,'.local/installation.json'),{root});const file=path.join(root,'.local/updates/active.json');write(file,{current:NEW,pending:true,attempted:Date.now()});let target;const app={relaunch:value=>{target=value.args[0];},exit:()=>{}};bootstrap(app,root);assert.equal(target,dir);bootstrap(app,root);assert.equal(read(file).current,null);bootstrap(app,dir);assert.equal(target,root);});
test('missing installation marker is refused and a bookkeeping write failure cannot prevent startup',t=>{const root=setup(t),dir=versionPath(root,NEW);artifacts(dir);write(path.join(dir,'.local/ready.json'),{revision:NEW});assert.equal(validVersion(root,NEW),false);write(path.join(dir,'.local/installation.json'),{root});const file=path.join(root,'.local/updates/active.json');write(file,{current:NEW,pending:true});const rename=fs.renameSync;try{fs.renameSync=(a,b)=>{if(b===file)throw Error('EPERM fixture');return rename(a,b);};assert.match(bootstrap({relaunch:()=>assert.fail('must run existing checkout'),exit:()=>{}},root),/EPERM fixture/);}finally{fs.renameSync=rename;}});
test('large command output is bounded without terminating the build and timeout stops its process',async t=>{const root=setup(t);const output=await command(process.execPath,['-e','process.stdout.write("x".repeat(3*1024*1024))'],root);assert.equal(output.length,65536);await assert.rejects(command(process.execPath,['-e','setInterval(()=>{},1000)'],root,200),/超时/);});
