const {EventEmitter}=require('node:events'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
class MessageQueue extends EventEmitter{
 constructor(store,runner,file){super();this.store=store;this.runner=runner;this.file=file;this.running=false;this.paused=false;try{this.items=JSON.parse(fs.readFileSync(file,'utf8'));if(!Array.isArray(this.items))this.items=[];}catch{this.items=[];}for(const item of this.items)if(item.status==='sending'){item.status='held';item.error='上次发送未确认，请核对记录后重试';}}
 save(){fs.mkdirSync(path.dirname(this.file),{recursive:true});const tmp=this.file+'.tmp';fs.writeFileSync(tmp,JSON.stringify(this.items));fs.renameSync(tmp,this.file);this.emit('change',this.items);}
 enqueue(taskId,text,images=[],options={}){const task=this.store.get(taskId);if(task.state==='unknown')throw Error('请先核对工作目录。');if(!text.trim()||text.length>60000)throw Error('请输入 1–60000 字的指令。');if(this.items.length>=100)throw Error('待发送消息过多');const item={id:crypto.randomUUID(),taskId,text,images,options,at:new Date().toISOString(),status:'waiting'};this.items.push(item);this.save();this.pump();return item;}
 cancel(id){if(this.items.find(i=>i.id===id)?.status==='sending')throw Error('消息已开始执行，请使用停止按钮');this.items=this.items.filter(i=>i.id!==id);this.save();}
 retry(id){const item=this.items.find(i=>i.id===id&&i.status==='held');if(item){item.status='waiting';delete item.error;this.save();this.pump();}}
 async pump(){if(this.running||this.runner.active||this.paused)return;this.running=true;try{while(!this.runner.active&&!this.paused){const index=this.items.findIndex(i=>{try{return i.status==='waiting'&&!['unknown','running','stopping'].includes(this.store.get(i.taskId).state);}catch{i.status='held';i.error='任务不存在';return false;}});if(index<0)break;const item=this.items[index];item.status='sending';this.save();try{await this.runner.run(item.taskId,item.text,item.images,item.options||{});this.items=this.items.filter(i=>i.id!==item.id);if(['failed','unknown','paused'].includes(this.store.get(item.taskId).state)){for(const queued of this.items.filter(i=>i.taskId===item.taskId)){queued.status='held';queued.error='上一轮未正常完成，请确认后重试';}}}catch(e){for(const pending of this.items.filter(i=>i.taskId===item.taskId)){pending.status='held';pending.error=e.message;}}this.save();}}catch(e){this.emit('failure',e);}finally{this.running=false;}}
}
module.exports={MessageQueue};
