import React,{useEffect,useRef,useState} from 'react';
import {Plus,ChevronDown,MessageSquare,FolderPlus,FolderOpen,ArrowUpRight} from 'lucide-react';
import {tr} from './i18n.js';
import './project-creation.css';
export function NewEntry({onConversation,onProject}){
 const [open,setOpen]=useState(false),root=useRef(null),trigger=useRef(null);
 useEffect(()=>{const close=e=>{if(!root.current?.contains(e.target))setOpen(false);};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close);},[]);
 useEffect(()=>{if(open)root.current.querySelector('[role="menuitem"]')?.focus();},[open]);
 return <div className="new-entry" ref={root} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);trigger.current.focus();}if(open&&['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const items=[...root.current.querySelectorAll('[role="menuitem"]')],index=items.indexOf(document.activeElement);items[e.key==='Home'?0:e.key==='End'?items.length-1:(index+(e.key==='ArrowUp'?-1:1)+items.length)%items.length]?.focus();}}} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setOpen(false);}}>
  <button ref={trigger} className="primary new-task" aria-haspopup="menu" aria-expanded={open} onClick={()=>setOpen(v=>!v)}><Plus size={18}/><span>{tr('新建')}</span><ChevronDown size={15}/></button>
  {open&&<div className="new-entry-menu" role="menu" aria-label={tr('新建')}><button role="menuitem" onClick={()=>{setOpen(false);onConversation();}}><MessageSquare size={18}/><span><strong>{tr('新对话')}</strong><small>{tr('直接开始，或选择一个项目')}</small></span></button><button role="menuitem" onClick={()=>{setOpen(false);onProject();}}><FolderPlus size={18}/><span><strong>{tr('新项目')}</strong><small>{tr('为多条对话保存一个工作目录')}</small></span></button></div>}
 </div>;
}
export function NewProject({Modal,onClose,onCreate}){
 const [kind,setKind]=useState('create'),[name,setName]=useState(''),[parent,setParent]=useState(''),[cwd,setCwd]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const folder=kind==='create'?parent:cwd;
 async function pick(){try{const dir=await window.prism.pickDirectory();if(!dir)return;if(kind==='create')setParent(dir);else{setCwd(dir);if(!name.trim())setName(dir.split(/[\\/]/).filter(Boolean).pop()||'');}setError('');}catch(e){setError(e.message);}}
 async function submit(e){e.preventDefault();if(busy)return;setBusy(true);setError('');try{await onCreate({kind,name,parent,cwd});}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <Modal title={tr('新项目')} onClose={onClose} dismissible={!busy}><form className="new-project-form" onSubmit={submit}><p className="muted">{tr('项目保存一个工作目录，多条对话可以在这里继续。')}</p><fieldset className="project-kind" disabled={busy}><legend>{tr('项目文件夹')}</legend>{[['create','创建新文件夹'],['existing','使用已有文件夹']].map(([value,label])=><label key={value}><input type="radio" name="project-kind" value={value} checked={kind===value} onChange={()=>{setKind(value);setError('');}}/>{tr(label)}</label>)}</fieldset><label>{tr('项目名称')}<input autoFocus required maxLength={100} value={name} disabled={busy} onChange={e=>setName(e.target.value)}/></label><label>{tr(kind==='create'?'保存位置':'项目文件夹')}<div className="field-row"><input required value={folder} disabled={busy} placeholder={tr('选择文件夹')} onChange={e=>kind==='create'?setParent(e.target.value):setCwd(e.target.value)}/><button type="button" className="outline" aria-label={tr('选择文件夹')} disabled={busy} onClick={pick}><FolderOpen size={18}/></button></div></label><p className="project-destination muted">{kind==='create'&&parent&&name.trim()?<>{tr('将创建：')}<span dir="auto">{parent.replace(/[\\/]$/,'')}/{name.trim()}</span></>:tr(kind==='existing'?'使用现有文件，不会移动或复制。':'在所选位置创建同名文件夹。')}</p>{error&&<p role="alert" className="error">{tr(error.replace(/^Error invoking remote method '[^']+': (?:Error: )?/,''))}</p>}<footer><button type="button" className="quiet" disabled={busy} onClick={onClose}>{tr('取消')}</button><button className="primary" type="submit" disabled={busy||!name.trim()||!folder.trim()}>{tr(busy?'正在保存…':'创建项目')}<ArrowUpRight size={17}/></button></footer></form></Modal>;
}
