import React,{useEffect,useState} from 'react';
import {ChevronDown,FolderOpen,Check,X,Plus} from 'lucide-react';
import {tr} from './i18n.js';
import {sidebarGroups} from './sidebar-groups.js';
export default function SidebarTasks({tasks,renderTask,projectNames={},onRenameProject,onMoveTask,savedProjects=[],projectPreferences={},onProjectMenu,onProjectAction,revealedProject,onNewConversation,onNewProject}){
 const [dropTarget,setDropTarget]=useState(''),[moveError,setMoveError]=useState('');
 const [editing,setEditing]=useState(null),[name,setName]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
 async function save(e){e.preventDefault();if(!name.trim()||saving)return;setSaving(true);try{if(editing.kind==='section')await onProjectAction(editing.path,'section',name.trim());else await onRenameProject(editing.path,name.trim());setEditing(null);setError('');}catch(e){setError(e.message);}finally{setSaving(false);}}
 const [collapsed,setCollapsed]=useState(()=>{try{return {pinned:true,projects:true,recent:true,...JSON.parse(localStorage.getItem('prism-sidebar-folds')||'{}')};}catch{return {pinned:true,projects:true,recent:true};}});
 const toggle=key=>setCollapsed(old=>{const next={...old,[key]:!old[key]};try{localStorage.setItem('prism-sidebar-folds',JSON.stringify(next));}catch{}return next;});
 useEffect(()=>{if(!revealedProject)return;setCollapsed(old=>{const next={...old,projects:false,['project:'+revealedProject.cwd.replaceAll('\\','/').replace(/\/$/,'').toLowerCase()]:false};try{localStorage.setItem('prism-sidebar-folds',JSON.stringify(next));}catch{}return next;});},[revealedProject]);
 function section(group,nested=false){const label=group.path?(projectNames[group.key.slice(8)]||group.label):nested?group.label:tr(group.label);const count=group.tasks.length+(group.groups||[]).reduce((n,g)=>n+g.tasks.length,0);return <section className={`sidebar-section${nested?' nested':''}${dropTarget===group.key?' drop-target':''}`} key={group.key} onDragOver={group.path?e=>{if(e.dataTransfer.types.includes('application/x-prism-task')){e.preventDefault();e.stopPropagation();e.dataTransfer.dropEffect='move';setDropTarget(group.key);}}:undefined} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget))setDropTarget('');}} onDrop={group.path?async e=>{e.preventDefault();e.stopPropagation();setDropTarget('');const id=e.dataTransfer.getData('application/x-prism-task');if(!tasks.some(t=>t.id===id))return;try{await onMoveTask(id,group.path);setMoveError('');setCollapsed(old=>{const next={...old,projects:false,[group.key]:false};try{localStorage.setItem('prism-sidebar-folds',JSON.stringify(next));}catch{}return next;});}catch(error){setMoveError(error.message);}}:undefined}>
  {editing?.key===group.key?<form className="task-rename project-rename" onSubmit={save}><input autoFocus aria-label={tr(editing.kind==='section'?'分区名称':'项目名称')} value={name} maxLength={100} disabled={saving} onChange={e=>setName(e.target.value)} onKeyDown={e=>{if(e.key==='Escape'&&!saving){setEditing(null);setError('');}}}/><button aria-label={tr('保存名称')} disabled={saving||!name.trim()}><Check size={14}/></button><button type="button" aria-label={tr('取消')} disabled={saving} onClick={()=>{setEditing(null);setError('');}}><X size={14}/></button>{error&&<small role="alert">{error}</small>}</form>:<div className="sidebar-section-heading" onContextMenu={group.path?async e=>{e.preventDefault();e.stopPropagation();try{const choice=await onProjectMenu(group.path);if(!choice)return;if(choice.action==='rename'||choice.action==='section-new'){setEditing({...group,kind:choice.action==='rename'?'rename':'section'});setName(choice.action==='rename'?label:'');setError('');}else await onProjectAction(group.path,choice.action,choice.value);}catch(error){setMoveError(error.message);}}:undefined}><button className="sidebar-section-toggle" aria-expanded={!collapsed[group.key]} title={group.path} onClick={()=>toggle(group.key)}><ChevronDown size={13} className={collapsed[group.key]?'folded':''}/>{group.path&&<FolderOpen size={14}/>}<span>{label}</span><small>{group.key==='projects'?group.groups.length:count}</small></button>{(group.path||group.key==='projects')&&<button className="project-create-button" aria-label={group.path?tr('在 {project} 中新建对话',{project:label}):tr('新项目')} title={tr(group.path?'新对话':'新项目')} onClick={()=>group.path?onNewConversation(group.path):onNewProject()}><Plus size={15}/></button>}</div>}
  {!collapsed[group.key]&&<div className="sidebar-section-content">{group.tasks.map(renderTask)}{group.groups?.map(g=>section(g,true))}{!count&&!group.groups?.length&&<p className="sidebar-empty">{tr('暂无任务')}</p>}</div>}
 </section>;}
 return <>{moveError&&<p role="alert" className="sidebar-empty">{moveError}</p>}{sidebarGroups(tasks,savedProjects,projectPreferences).map(group=>section(group))}</>;
}
