import React,{useEffect,useState} from 'react';
import {tr} from './i18n.js';
const labels={idle:'尚未检查更新',checking:'正在检查更新',current:'已是最新版本',available:'发现新版本',preparing:'正在准备新版',ready:'新版已就绪',restarting:'正在重启更新',error:'更新未完成'};
export default function UpdateSettings(){
 const [state,setState]=useState({}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{window.prism.updateStatus().then(setState).catch(e=>setError(e.message));return window.prism.subscribe(({type,value})=>{if(type==='app-update')setState(value);});},[]);
 const action=async method=>{setBusy(true);setError('');try{setState(await window.prism[method]()||state);}catch(e){setError(e.message.replace(/^Error invoking remote method '[^']+': Error: /,''));}finally{setBusy(false);}};
 const changeAutomatic=async value=>{const before=state;setBusy(true);setState({...state,automatic:value});try{setState(await window.prism.automaticUpdates(value));}catch(e){setState(before);setError(e.message);}finally{setBusy(false);}};
 return <section className="update-settings" aria-label={tr('软件更新')}><strong>{tr('软件更新')}</strong><label><span>{tr('自动检查更新')}</span><input type="checkbox" checked={state.automatic!==false} disabled={busy} onChange={e=>changeAutomatic(e.target.checked)}/></label><p>{tr('发现新版时亮起蓝点，确认后下载并更新。')}</p><p role="status">{tr(labels[state.status]||labels.idle)}{state.detail?` · ${tr(state.detail)}`:''}</p><small>{tr('当前版本')} · {state.current?.slice(0,8)||'—'}{state.latest&&state.latest!==state.current?` → ${state.latest.slice(0,8)}`:''}</small>{state.checkedAt&&<small>{tr('上次检查')} · {new Date(state.checkedAt).toLocaleString()}</small>}<div className="update-actions"><button disabled={busy||['checking','preparing','restarting'].includes(state.status)} onClick={()=>action('checkUpdates')}>{tr('检查更新')}</button>{(state.status==='available'||state.status==='error'&&state.latest&&state.latest!==state.current)&&<button disabled={busy} onClick={()=>action('prepareUpdate')}>{tr('下载并准备')}</button>}{state.status==='ready'&&<button disabled={busy} onClick={()=>action('installUpdate')}>{tr('更新并重启')}</button>}</div>{(error||state.error)&&<p role="alert">{tr(error||state.error)}</p>}</section>;
}
